### ISSUE TITLE
v2.2.7.2 does not compile on Ruby 3.3

### ISSUE THREAD

**Issue by denisdefreyne** [davidfstr/rdiscount#160]
On Ruby 3.3 (released a few days ago), rdiscount does not compile.

```
[snip]
gethopt.c:48:13: error: parameter 'val' was not declared, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
   48 | hopterr(ctx,val)
      |             ^
   49 | struct h_context *ctx;
   50 | {
[snip
```

[Full log is here](https://gist.github.com/denisdefreyne/15091779e5ada3374e3c42c42b516a81).

rdiscount version: 2.2.7.2

Other useful bits (perhaps):

```
% uname -a
Darwin Osmium.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:59:33 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8112 arm64

% ruby --version
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]

% gem --version
3.5.3
```

**Comment by davidfstr** [comment]
Thanks for your report! I'll plan to take a look this weekend, along with 2 other items reported on the latest 2.2.7.2 release.

**Comment by davidfstr** [comment]
Fixed in RDiscount 2.2.7.3, which was just released
